# Rewrite rules (proxy configuration)
[[redirects]]
  from = "/docs"
  to = "https://proxy.gitbook.site/sites/site_qixqW"
  status = 200
  force = true

[[redirects]]
  from = "/docs/*"
  to = "https://proxy.gitbook.site/sites/site_qixqW/:splat"
  status = 200
  force = true
